# Use postgres/example user/password credentials
version: '3.1'

services:

  server:
    build: .
    container_name: spa_server
    restart: "no"
    ports:
      - "2137:2137"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - hidden

  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    networks:
      - hidden

  pdfparser:
    image: ucrel/ucrel-science-parse:3.0.1
    init: true
    restart: always
    ports:
      - ${PDFPARSER_PORT}:${PDFPARSER_PORT}
    networks:
      - hidden

  sslproxy:
    build: ./nginx
    restart: always
    ports:
      - "8000:8000"
    networks:
      - outside
      - hidden
    volumes:
      - /etc/letsencrypt/live/backend.spaserver.dev:/etc/nginx/certs

networks:
  hidden:
    internal: true
  outside: